spring.application.name=TallerDespliegue
server.port=8090
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dbdespliegue}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_apidos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jackson.serialization.fail-on-empty-beans=false
logging.level.org.hibernate=ERROR
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
